# -*- coding: utf-8 -*-
"""Tugas1_ddp_senin_0110122192_Abdullah Hafidz Ramadhan_SI13.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199XYuEhMOQQJ3AzJ29s_VrZ3J_Iz-cz_
"""

#dictionary
p1 = {'Nama':'Budi', 'Jabatan':'Manager', 'Agama':'Islam', 'Status':'Menikah'}
p2 = {'Nama':'Siti', 'Jabatan':'Asisten', 'Agama':'Islam', 'Status':'Menikah'}
p3 = {'Nama':'I Gede', 'Jabatan':'Supervisor', 'Agama':'Hindu', 'Status':'Menikah'}
p4 = {'Nama':'Joko', 'Jabatan':'Staff', 'Agama':'Islam', 'Status':'Belum Menikah'}
p5 = {'Nama':'Alex', 'Jabatan':'Staff', 'Agama':'Kristen', 'Status':'Belum Menikah'}

#list
ar_pegawai = [p1,p2,p3,p4,p5]

#Nested Loop
for pegawai in ar_pegawai:
    for key, data in pegawai.items():
      #mencari gapok pegawai
      gaji = pegawai['Jabatan']
      if gaji == 'Manager':
          gajipokok = 15000000
      elif gaji == 'Asisten Manager':    
          gajipokok = 10000000
      elif gaji == 'Supervisor':
          gajipokok = 7000000
      else:
          gajipokok = 4000000
          #mencari elemen gaji lain
          tunjanganjabatan = 0.3 * gajipokok
          bpjs = 0.1 * gajipokok
          tunjangankeluarga = pegawai['Status']
          ket = (0, gajipokok * 0.1) [tunjangankeluarga == 'Menikah']
          gajikotor = gajipokok + tunjanganjabatan + bpjs + ket
          Zakatprofesi = pegawai['Agama']
          Zakatprofesi2 = (0,0.025 * gajipokok) [gajikotor >= 7000000 and zakatprofesi == 'Islam']
          gajibersih = gajikotor - Zakatprofesi2
          print(key,':', data)
          print('Gaji Pokok \t\t:', gajipokok, 
                '\nTunjangan Jabatan \t:', tunjanganjabatan, 
                '\nBpjs \t\t\t:', bpjs, 
                '\nTunjangan Keluarga \t:', ket, 
                '\nGaji Kotor\t\t:', gajikotor, 
                '\nZakat Profesi \t\t:', Zakatprofesi2,
                '\nGaji Bersih \t\t:', gajibersih,
                '\n-------------')